baseURL = "https://evilrobots.ai/"
publishdir = "docs"
languageCode = "en-au"
title = "evil robots pty ltd"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/er-logo-transparent-300x46.png"
    mobile_height = "46px"
    mobile_width = "300px"
    desktop = "images/er-logo-transparent-300x46.png"
    desktop_height = "46px"
    desktop_width = "300px"
    alt = "evil robots"

  [params.homepage_meta_tags]
    meta_description = "evil robots pty ltd is a robotics r&d company based in Sydney, Australia."
    meta_og_title = "evil robots pty ltd"
    meta_og_type = "website"
    meta_og_url = "https://evilrobots.ai/"
    meta_og_image = "https://raw.githubusercontent.com/evilrobots-ai/evilrobots-ai.github.io/main/static/images/k3lpie-detail.jpg"
    meta_og_description = "evil robots pty ltd is a robotics r&d company based in Sydney, Australia."
    meta_twitter_card = "summary"
    meta_twitter_site = "@evilrobotsAI"
    meta_twitter_creator = "@evilrobotsAI"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Merch"
    url = "https://evilrobots.myspreadshop.com.au/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
