baseURL = "https://evilrobots.ai"
languageCode = "en-au"
title = "evil robots pty ltd"
themesDir = "themes"
theme = "ananke"
publishdir = "docs"
disableKinds = ["taxonomy", "term", "RSS"]

DefaultContentLanguage = "en"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "evil robots pty ltd"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = ""
  favicon = "favicon.png"
  site_logo = "/images/er-logo-transparent-inv-300x46.png"
  description = "Practical autonomy infrastructure."
  background_color_class = "bg-black"
  body_classes = "site-body bg-near-white"
  custom_css = ["site.css"]
  preview_mode = false

[[params.links]]
  url = "/privacy/"
  description = "Privacy"

[[params.links]]
  url = "/conditions/"
  description = "Terms"

[[params.links]]
  url = "/contact/"
  description = "Contact"

[[params.links]]
  description = "evil robots ® is a registered trademark"

[[params.links]]
  description = "ABN 21667313911"

[[menu.main]]
  name = "blackbot"
  url = "/blackbot/"
  weight = 10

[[menu.main]]
  name = "company"
  url = "/company/"
  weight = 20

[[menu.main]]
  name = "work"
  url = "/work/"
  weight = 30

[[menu.main]]
  name = "contact"
  url = "/contact/"
  weight = 40

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/evilrobotsAI"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/evilrobots-ai"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/company/evilrobots/"
